"""create_core_data_models

Revision ID: 35e9475d9a7d
Revises: 5668fce3f07a
Create Date: 2026-08-31 14:19:42.002501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35e9475d9a7d'
down_revision: Union[str, Sequence[str], None] = '5668fce3f07a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_resume_text', sa.Text(), nullable=False),
    sa.Column('extracted_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_profile_id'), 'candidate_profile', ['id'], unique=False)
    op.create_table('role_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_jd_text', sa.Text(), nullable=False),
    sa.Column('extracted_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_profile_id'), 'role_profile', ['id'], unique=False)
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_profile_id', sa.Integer(), nullable=False),
    sa.Column('role_profile_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'ABORTED', name='session_status', native_enum=False), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('policy_version', sa.String(length=50), nullable=False),
    sa.Column('engine_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profile.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_profile_id'], ['role_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_id'), 'session', ['id'], unique=False)
    op.create_table('evaluation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('dimension', sa.String(length=100), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('evidence_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rubric_version', sa.String(length=50), nullable=False),
    sa.Column('model_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_id'), 'evaluation', ['id'], unique=False)
    op.create_index(op.f('ix_evaluation_session_id'), 'evaluation', ['session_id'], unique=False)
    op.create_table('state_transition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('from_state', sa.String(length=100), nullable=False),
    sa.Column('to_state', sa.String(length=100), nullable=False),
    sa.Column('proposed_by_llm', sa.Boolean(), nullable=False),
    sa.Column('was_validated', sa.Boolean(), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('model_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_state_transition_id'), 'state_transition', ['id'], unique=False)
    op.create_index(op.f('ix_state_transition_session_id'), 'state_transition', ['session_id'], unique=False)
    op.create_table('turn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.Enum('CANDIDATE', 'MIKI', name='speaker', native_enum=False), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_turn_id'), 'turn', ['id'], unique=False)
    op.create_index(op.f('ix_turn_session_id'), 'turn', ['session_id'], unique=False)
    op.create_table('claim',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('turn_id', sa.Integer(), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turn_id'], ['turn.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_id'), 'claim', ['id'], unique=False)
    op.create_index(op.f('ix_claim_session_id'), 'claim', ['session_id'], unique=False)
    op.create_index(op.f('ix_claim_turn_id'), 'claim', ['turn_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('turn_id', sa.Integer(), nullable=False),
    sa.Column('evidence_text', sa.Text(), nullable=False),
    sa.Column('evidence_type', sa.Enum('SUPPORTS', 'CONTRADICTS', 'VAGUE', name='evidence_type', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claim.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turn_id'], ['turn.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_claim_id'), 'evidence', ['claim_id'], unique=False)
    op.create_index(op.f('ix_evidence_id'), 'evidence', ['id'], unique=False)
    op.create_index(op.f('ix_evidence_turn_id'), 'evidence', ['turn_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_turn_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_claim_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_claim_turn_id'), table_name='claim')
    op.drop_index(op.f('ix_claim_session_id'), table_name='claim')
    op.drop_index(op.f('ix_claim_id'), table_name='claim')
    op.drop_table('claim')
    op.drop_index(op.f('ix_turn_session_id'), table_name='turn')
    op.drop_index(op.f('ix_turn_id'), table_name='turn')
    op.drop_table('turn')
    op.drop_index(op.f('ix_state_transition_session_id'), table_name='state_transition')
    op.drop_index(op.f('ix_state_transition_id'), table_name='state_transition')
    op.drop_table('state_transition')
    op.drop_index(op.f('ix_evaluation_session_id'), table_name='evaluation')
    op.drop_index(op.f('ix_evaluation_id'), table_name='evaluation')
    op.drop_table('evaluation')
    op.drop_index(op.f('ix_session_id'), table_name='session')
    op.drop_table('session')
    op.drop_index(op.f('ix_role_profile_id'), table_name='role_profile')
    op.drop_table('role_profile')
    op.drop_index(op.f('ix_candidate_profile_id'), table_name='candidate_profile')
    op.drop_table('candidate_profile')
    # ### end Alembic commands ###
